import type { Metadata } from "next";
import { oswald,dm_Sans,inter,Gilroy,plus_Jakarta_Sans,sofia_pro } from "@/lib/fonts/fonts";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"], variable : "--font-inter" ,display: 'swap',});
// const oswald = Oswald({ subsets: ["latin"], variable : "--font-oswald" , display: 'swap', });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${oswald.variable} ${inter.variable} ${dm_Sans.variable} ${Gilroy.variable} ${plus_Jakarta_Sans.variable} ${sofia_pro.variable}`}>{children}</body>
    </html>
  );
}
